# Generated by basic_api_automation.py. Performs a GET request.
[CmdletBinding()]
param([string]$Url)

$ErrorActionPreference = 'Stop'
$ScriptPath = Join-Path $PSScriptRoot 'basic_api_automation.py'
$PyLauncher = Get-Command py.exe -ErrorAction SilentlyContinue
$Arguments = @()
if ($PyLauncher) { $PythonCommand = $PyLauncher.Source; $Arguments += '-3' } else { $PythonCommand = 'python.exe' }
$Arguments += $ScriptPath
if ($Url) { $Arguments += @('--url', $Url) }
& $PythonCommand @Arguments
exit $LASTEXITCODE
