# Generated by service_monitor.py.
[CmdletBinding()]
param([switch]$NoRestart)

$ErrorActionPreference = 'Stop'
$ScriptPath = Join-Path $PSScriptRoot 'service_monitor.py'
$PyLauncher = Get-Command py.exe -ErrorAction SilentlyContinue

if ($PyLauncher) {
    $Arguments = @('-3', $ScriptPath)
    if ($NoRestart) { $Arguments += '--no-restart' }
    & $PyLauncher.Source @Arguments
} else {
    $Arguments = @($ScriptPath)
    if ($NoRestart) { $Arguments += '--no-restart' }
    & python.exe @Arguments
}

exit $LASTEXITCODE
