# Generated by security_automation.py. Performs read-only security checks.
[CmdletBinding()]
param([switch]$RefreshBaseline)

$ErrorActionPreference = 'Stop'
$ScriptPath = Join-Path $PSScriptRoot 'security_automation.py'
$PyLauncher = Get-Command py.exe -ErrorAction SilentlyContinue

if ($PyLauncher) {
    $Arguments = @('-3', $ScriptPath)
    if ($RefreshBaseline) { $Arguments += '--refresh-baseline' }
    & $PyLauncher.Source @Arguments
} else {
    $Arguments = @($ScriptPath)
    if ($RefreshBaseline) { $Arguments += '--refresh-baseline' }
    & python.exe @Arguments
}

exit $LASTEXITCODE
