# Generated by backup_automation.py.
[CmdletBinding()]
param([switch]$DryRun, [switch]$SkipRetention)

$ErrorActionPreference = 'Stop'
$ScriptPath = Join-Path $PSScriptRoot 'backup_automation.py'
$PyLauncher = Get-Command py.exe -ErrorAction SilentlyContinue
$Arguments = @()
if ($PyLauncher) { $PythonCommand = $PyLauncher.Source; $Arguments += '-3' } else { $PythonCommand = 'python.exe' }
$Arguments += $ScriptPath
if ($DryRun) { $Arguments += '--dry-run' }
if ($SkipRetention) { $Arguments += '--skip-retention' }
& $PythonCommand @Arguments
exit $LASTEXITCODE
