# Generated by configuration_backup.py.
[CmdletBinding()]
param([switch]$DryRun)

$ErrorActionPreference = 'Stop'
$ScriptPath = Join-Path $PSScriptRoot 'configuration_backup.py'
$PyLauncher = Get-Command py.exe -ErrorAction SilentlyContinue
$Arguments = @()
if ($PyLauncher) { $PythonCommand = $PyLauncher.Source; $Arguments += '-3' } else { $PythonCommand = 'python.exe' }
$Arguments += $ScriptPath
if ($DryRun) { $Arguments += '--dry-run' }
& $PythonCommand @Arguments
exit $LASTEXITCODE
