# Generated by server_health_monitor.py. Performs read-only health checks.
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$ScriptPath = Join-Path $PSScriptRoot 'server_health_monitor.py'
$PyLauncher = Get-Command py.exe -ErrorAction SilentlyContinue

if ($PyLauncher) {
    & $PyLauncher.Source -3 $ScriptPath
} else {
    & python.exe $ScriptPath
}

exit $LASTEXITCODE
