# Generated by user_account_automation.py. Audits by default.
[CmdletBinding()]
param([switch]$Apply)

$ErrorActionPreference = 'Stop'
$ScriptPath = Join-Path $PSScriptRoot 'user_account_automation.py'
$PyLauncher = Get-Command py.exe -ErrorAction SilentlyContinue

if ($PyLauncher) {
    $Arguments = @('-3', $ScriptPath)
    if ($Apply) { $Arguments += '--apply' }
    & $PyLauncher.Source @Arguments
} else {
    $Arguments = @($ScriptPath)
    if ($Apply) { $Arguments += '--apply' }
    & python.exe @Arguments
}

exit $LASTEXITCODE
