# Generated by certificate_domain_monitoring.py.
[CmdletBinding()]
param([switch]$NoEmail)

$ErrorActionPreference = 'Stop'
$ScriptPath = Join-Path $PSScriptRoot 'certificate_domain_monitoring.py'
$PyLauncher = Get-Command py.exe -ErrorAction SilentlyContinue
$Arguments = @()
if ($PyLauncher) { $PythonCommand = $PyLauncher.Source; $Arguments += '-3' } else { $PythonCommand = 'python.exe' }
$Arguments += $ScriptPath
if ($NoEmail) { $Arguments += '--no-email' }
& $PythonCommand @Arguments
exit $LASTEXITCODE
