# Generated by deployment_automation.py.
[CmdletBinding()]
param([switch]$DryRun, [switch]$NoRestart)

$ErrorActionPreference = 'Stop'
$ScriptPath = Join-Path $PSScriptRoot 'deployment_automation.py'
$PyLauncher = Get-Command py.exe -ErrorAction SilentlyContinue
$Arguments = @()
if ($PyLauncher) { $PythonCommand = $PyLauncher.Source; $Arguments += '-3' } else { $PythonCommand = 'python.exe' }
$Arguments += $ScriptPath
if ($DryRun) { $Arguments += '--dry-run' }
if ($NoRestart) { $Arguments += '--no-restart' }
& $PythonCommand @Arguments
exit $LASTEXITCODE
